### ISSUE TITLE
CMD Output mangled

### ISSUE THREAD

**Issue by Tannister** [AntonioDePau/GHDS_ModdingTool#19]
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/b6efe134-3e08-4321-8fae-8f19626646d4)

The output that get written to the cmd mangles itself with each replacement file.

From what i can see while running the tool, it seems to always write on line2 of the CMD box, regardless of what is already there.

**Comment by AntonioDePau** [comment]
This is caused by the fix for the OoR exception: https://github.com/AntonioDePau/GHDS_ModdingTool/commit/28a341fdd6045bd68531a54941623b9a955d1b85

But it's fine on my side. There's a general issue on your machine (Windows 11 might be the cause) regarding console ouput. I'll need to investigate the difference between Windows 10 and 11 when it comes to this.

**Comment by AntonioDePau** [comment]
Hey, so this is indeed an issue with Windows 11.
It appears to be caused by the Windows Terminal (default command/console app on Windows 11) to behave incorrectly with console methods.

Can you try to change your default console app from Windows Terminal to anything else (Windows Console Host, or Powershell)? Here's a guide: https://winaero.com/windows-11-change-console-to-windows-terminal-or-command-prompt/
